name: Update Landing Zone Accelerator Config

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write

jobs:
  update:
    name: Update Landing Zone Accelerator Config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_UPDATE_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Zip config files
        run: zip -qq aws-accelerator-config.zip *.yaml

      - name: Upload zipped config to S3
        run: aws s3 cp aws-accelerator-config.zip s3://aws-accelerator-config-${{ vars.AWS_ACCOUNT_ID }}-${{ vars.AWS_REGION }}/zipped/aws-accelerator-config.zip

      - name: Trigger Codepipeline
        run: aws codepipeline start-pipeline-execution --name AWSAccelerator-Pipeline